export const projects = [
  {
    folder: "./assets/project1/",
    images: [
      "main1.jpg",
      "main2.jpg",
      "main3.jpg",
      "main4.jpg",
      "main5.jpg",
      "main6.jpg",
      "main7.jpg",
      "main8.jpg",
      "main9.jpg",
      "main10.jpg",
      "main11.jpg",
      "main12.jpg",
    ],
    title: "ADtech",
    githubLink: "#",
    githubTitle: "Private repo",
    tech : ["Flutter","firebase"],
    overview:
      "An app that aims to digitize all the work in dental universities, to help them collect data of their patients easily and store it with the best way possible",
  },
  {
    folder: "./assets/project2/",
    images: [
      "main19.jpg",
      "main18.jpg",
      "main17.jpg",
      "main16.jpg",
      "main15.jpg",
      "main14.jpg",
      "main13.jpg",
      "main12.jpg",
      "main11.jpg",
      "main10.jpg",
      "main9.jpg",
      "main8.jpg",
      "main7.jpg",
      "main6.jpg",
      "main5.jpg",
      "main4.jpg",
      "main3.jpg",
      "main2.jpg",
      "main1.jpg",
    ],
    title: "Site management",
    githubLink: "#",
    githubTitle: "Private repo",
    tech : ["Flutter","firebase"],
    overview:
      "This project is for an entrepreneur to help him manage his work. There are two applications, one for his site managers where they can add all the transactions they did such as buying food and paying simple workers. The second application is an admin app for the entrepreneur, he can control all their transactions sorted by site and type, he can also see statistics about all their transactions",
  },
  {
    folder: "./assets/project3/",
    images: [
      "main1.jpg",
      "main2.jpg",
      "main3.jpg",
      "main4.jpg",
      "main5.jpg",
      "main6.jpg",
      "main7.jpg",
      "main8.jpg",
      "main9.jpg",
      "main10.jpg",
      "main11.jpg",
      "main12.jpg",
      "main13.jpg",
      "main14.jpg",
      "main15.jpg",
      "main16.jpg",
      "main17.jpg",
      "main18.jpg",
      "main19.jpg",
      "main20.jpg",
      "main21.jpg",
    ],
    title: "Cleaning App",
    githubLink: "#",
    githubTitle: "Private repo",
    tech : ["Flutter","firebase"],
    overview:
      "cleaning app is an app created for a virtual cleaning company , to help clients finding the available services offered by the company and make their demands",
  },
  {
    folder: "./assets/project4/",
    images: [
      "main1.jpg",
      "main2.jpg",
      "main3.jpg",
      "main4.jpg",
      "main5.jpg",
      "main6.jpg",
      "main7.jpg",
      "main8.jpg",
      "main9.jpg",
      "main10.jpg",
      "main11.jpg",
      "main12.jpg",
      "main13.jpg",
      "main14.jpg",
      "main15.jpg",
      "main16.jpg",
      "main17.jpg",
      "main18.jpg",
      "main19.jpg",
      "main20.jpg",
      "main21.jpg",
    ],
    title: "Free Classes",
    githubLink: "#",
    githubTitle: "Private repo",
    tech : ["Flutter","firebase"],
    overview:
      "Freeclasse is a solution that helps students find teachers and do online sessions to help them improve their studies",
  },
  {
    folder: "./assets/project5/",
    images: [
      "main1.jpg",
      "main2.jpg",
      "main3.jpg",
      "main4.jpg",
      "main5.jpg",
      "main6.jpg",
      "main7.jpg",
      "main8.jpg",
      "main9.jpg",
      "main10.jpg",
      "main11.jpg",
      "main12.jpg",
      "main13.jpg",
      "main14.jpg",
      "main15.jpg",
      "main16.jpg",
      "main17.jpg",
      "main18.jpg",
    ],
    title: "Dars delivery",
    githubLink: "#",
    githubTitle: "Private repo",
    tech : ["Flutter","firebase"],
    overview:
      "dars delivery is an app that link students with teachers to do online sessions through a google meet link or in person sessions by setting the location of the teacher using google maps , it also help them communicate through chat",
  },
  {
    folder: "./assets/project6/",
    images: [
      "main1.jpg",
      "main2.jpg",
      "main3.jpg",
      "main4.jpg",
      "main5.jpg",
      "main6.jpg",
      "main7.jpg",
      "main8.jpg",
      "main9.jpg",
      "main10.jpg",
      "main11.jpg",
      "main12.jpg",
      "main13.jpg",
      "main14.jpg",
    ],
    title: "Swalis App",
    githubLink: "#",
    githubTitle: "Private repo",
    tech : ["Flutter","firebase"],
    overview:
      "swalis app is an app for swalis , which is a company that produces cosmetic products here in algeria , the purpose of this app is to help the company offer its services to customers and get their commands . also there s some products that swalis buy them from suppliers and include its marc in them , so this app also has a side for suppliers to help them deal with the company",
  },
  {
    folder: "./assets/project7/",
    images: [
      "main1.jpg",
      "main2.jpg",
      "main3.jpg",
      "main4.jpg",
      "main5.jpg",
      "main6.jpg",
      "main7.jpg",
      "main8.jpg",
      "main9.jpg",
      "main10.jpg",
    ],
    title: "Chauffeur Cnas",
    githubLink: "#",
    githubTitle: "Private repo",
    tech : ["Flutter","firebase"],
    overview:
      "Chauffeur cnas  is an app for drivers of cnas (Caisse nationale des assurances sociales) to help them track the reel position of drivers and the road which they took to transport the patient , so that they can avoid fraud when they demand repayment",
  },
];
